version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  cooldown:
    semver-major-days: 14
    semver-minor-days: 7
    semver-patch-days: 2
  groups:
    bundler:
      patterns:
        - "*"
  open-pull-requests-limit: 10
