version: 2.1

orbs:
  snyk: snyk/snyk@2.2.0
  slack: circleci/slack@4.13.3

executors:
  cloud-platform-executor:
    resource_class: small
    docker:
      - image: ministryofjustice/cloud-platform-tools
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-crime-forms-team
          REPO_NAME: laa-crime-application-store
  test-executor:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.3.5-browsers

commands:
  install-requirements:
    steps:
      - restore_cache:
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-bundle-
      - run:
          name: Install gems
          command: |
            bundler_version=$(cat Gemfile.lock | tail -1 | tr -d " ")
            gem install bundler -v $bundler_version
            bundle config set path 'vendor/bundle'
            bundle check || bundle install --jobs=4 --retry=3
            bundle clean --force
      - save_cache:
          key: v1-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle
            - vendor/bundle

  run-tests:
    steps:
      - run:
          name: Run rspec tests
          command: |
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=filename)
            RUBYOPT=-W:no-deprecated \
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec/rspec.xml \
              -- ${TESTFILES}
      - store_test_results:
          path: /tmp/test-results/rspec
      - run:
          name: Stash coverage results
          command: |
            mkdir coverage_results
            cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage_results
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

  run-rubocop:
    steps:
      - run:
          name: Run rubocop
          command: bundle exec rubocop



jobs:
  lint-app:
    working_directory: ~/repo
    executor: test-executor
    steps:
      - checkout
      - install-requirements
      - run-rubocop

  test-app:
    working_directory: ~/repo
    executor: test-executor
    steps:
      - checkout
      - install-requirements
      - run-tests

workflows:
  version: 2

  test-opened-pr:
    jobs:
      - lint-app:
          filters:
            branches:
              ignore:
                - main
      - test-app:
          filters:
            branches:
              ignore:
                - main

  test-merged-pr:
    jobs:
      - lint-app:
          filters:
            branches:
              only:
                - main
      - test-app:
          filters:
            branches:
              only:
                - main
