module LaaCrimeFormsCommon
  class MainOffence
    attr_reader :type, :description

    OFFTYPEOATP = "Offences against the person".freeze
    OFFTYPEHARGO = "Homicide and related grave offences".freeze
    OFFTYPEFO = "Firearms Offences".freeze
    OFFTYPEPO = "Prison Offences".freeze
    OFFTYPESOAOAC = "Sexual offences and offences against children".freeze
    OFFTYPER = "Robbery".freeze
    OFFTYPEB = "Burglary".freeze
    OFFTYPECDAA = "Criminal Damage and Arson".freeze
    OFFTYPET = "Theft".freeze
    OFFTYPEFFAOOOD = "Fraud, Forgery and other Offences of Dishonesty".freeze
    OFFTYPEPOO = "Public order offences".freeze
    OFFTYPEDO = "Drug Offences".freeze
    OFFTYPEDAMVOO = "Driving and motor vehicle Offences (Other)".freeze
    OFFTYPEOTHER = "Other".freeze

    OFFENCES = [
      # Offences against the person
      [OFFTYPEOATP, "Assault (common)"],
      [OFFTYPEOATP, "Battery (common)"],
      [OFFTYPEOATP, "Assault occasioning actual bodily harm"],
      [OFFTYPEOATP, "Wounding or inflicting grievous bodily harm"],
      [OFFTYPEOATP, "Wounding or causing grievous bodily harm with intent"],
      [OFFTYPEOATP, "Making threats to kill"],
      [OFFTYPEOATP, "Racially aggravated assaults"],
      [OFFTYPEOATP, "Assault on constable in execution of duty"],
      [OFFTYPEOATP, "Resisting or wilfully obstructing constable"],
      [OFFTYPEOATP, "Assault with intention to resist arrest"],
      [OFFTYPEOATP, "Attempting to choke, suffocate, strangle etc"],
      [OFFTYPEOATP, "Endangering the safety of railway passengers"],
      [OFFTYPEOATP, "Causing bodily injury by explosives"],
      [OFFTYPEOATP, "Using gunpowder to explode, or sending to any person an explosive substance, or throwing corrosive fluid on a person, with intent to grievous bodily harm"],
      [OFFTYPEOATP, "Placing explosives etc., with intent to do bodily injury to any person"],
      [OFFTYPEOATP, "Making or having gunpowder etc., with intent to commit or enable any person to commit a felony"],
      [OFFTYPEOATP, "Causing miscarriage by poison, instrument"],
      [OFFTYPEOATP, "Supplying instrument etc. to cause miscarriage"],
      [OFFTYPEOATP, "Concealment of birth"],
      [OFFTYPEOATP, "Administering chloroform, laudanum etc."],
      [OFFTYPEOATP, "Administering poison etc. so as to endanger life"],
      [OFFTYPEOATP, "Administering poison with intent to injure etc."],
      [OFFTYPEOATP, "Circumcision of females"],
      [OFFTYPEOATP, "Kidnapping (common law)"],
      [OFFTYPEOATP, "Hostage taking"],
      [OFFTYPEOATP, "False imprisonment (common law)"],
      [OFFTYPEOATP, "Torture"],

      # Homicide and related grave offences
      [OFFTYPEHARGO, "Murder (common law)"],
      [OFFTYPEHARGO, "Manslaughter (common law)"],
      [OFFTYPEHARGO, "Causing death by dangerous driving"],
      [OFFTYPEHARGO, "Causing death by careless driving while under the influence of drink or drugs"],
      [OFFTYPEHARGO, "Aggravated vehicle taking resulting in death"],
      [OFFTYPEHARGO, "Killing in pursuance of suicide pact"],
      [OFFTYPEHARGO, "Complicity to suicide"],
      [OFFTYPEHARGO, "Soliciting to murder"],
      [OFFTYPEHARGO, "Child destruction"],
      [OFFTYPEHARGO, "Infanticide"],
      [OFFTYPEHARGO, "Abortion"],
      [OFFTYPEHARGO, "Supplying or procuring means for abortion"],

      # Firearms Offences
      [OFFTYPEFO, "Possession of firearm without certificate"],
      [OFFTYPEFO, "Possession or acquisition of shotgun without certificate"],
      [OFFTYPEFO, "Dealing in firearms"],
      [OFFTYPEFO, "Shortening of shotgun or possession of shortened shotgun"],
      [OFFTYPEFO, "Possession or acquisition of certain prohibited weapons etc."],
      [OFFTYPEFO, "Possession of firearm with intent to injure / endanger life"],
      [OFFTYPEFO, "Possession of firearm or imitation firearm with intent to cause fear of violence"],
      [OFFTYPEFO, "Use of firearm to resist arrest"],
      [OFFTYPEFO, "Possession of firearm with criminal intent"],
      [OFFTYPEFO, "Carrying loaded firearm in public place"],
      [OFFTYPEFO, "Trespassing with a firearm"],
      [OFFTYPEFO, "Possession of firearms by person convicted of crime"],
      [OFFTYPEFO, "Acquisition by or supply of firearms to person denied them"],
      [OFFTYPEFO, "Failure to comply with certificate when transferring firearm"],
      [OFFTYPEFO, "Shortening of smooth bore gun"],

      # Prison Offences
      [OFFTYPEPO, "Permitting an escape (common law)"],
      [OFFTYPEPO, "Rescue (common law)"],
      [OFFTYPEPO, "Escape (common law)"],
      [OFFTYPEPO, "Escaping from lawful custody without force (common law)"],
      [OFFTYPEPO, "Breach of prison (common law)"],
      [OFFTYPEPO, "Prison mutiny"],
      [OFFTYPEPO, "Assaulting prison officer whilst possessing firearm etc."],
      [OFFTYPEPO, "Harbouring escaped prisoners"],
      [OFFTYPEPO, "Assisting prisoners to escape Terrorist Offences"],
      [OFFTYPEPO, "Offences under the Terrorism Act 2000"],
      [OFFTYPEPO, "Offences against international protection of nuclear material"],
      [OFFTYPEPO, "Offences under the Northern Ireland"],

      # Sexual offences and offences against children
      [OFFTYPESOAOAC, "Offences under the Sexual Offences Act 2003"],
      [OFFTYPESOAOAC, "Child abduction by connected person"],
      [OFFTYPESOAOAC, "Child abduction by other person"],
      [OFFTYPESOAOAC, "Keeping brothel and related offences"],
      [OFFTYPESOAOAC, "Keeping a disorderly house"],
      [OFFTYPESOAOAC, "Soliciting"],
      [OFFTYPESOAOAC, "Taking, having etc. indecent photographs of children"],
      [OFFTYPESOAOAC, "Sexual intercourse with patients"],
      [OFFTYPESOAOAC, "Ill treatment of persons of unsound mind"],
      [OFFTYPESOAOAC, "Bigamy"],
      [OFFTYPESOAOAC, "Abuse of position of trust"],
      [OFFTYPESOAOAC, "Abandonment of children under two"],
      [OFFTYPESOAOAC, "Cruelty to persons under 16"],

      # Robbery
      [OFFTYPER, "Armed robbery"],
      [OFFTYPER, "Assault with weapon with intent to rob"],

      # Burglary
      [OFFTYPEB, "Burglary (domestic)"],
      [OFFTYPEB, "Going equipped to steal"],
      [OFFTYPEB, "Burglary (non-domestic)"],
      [OFFTYPEB, "Aggravated burglary"],

      # Criminal Damage and Arson
      [OFFTYPECDAA, "Criminal Damage"],
      [OFFTYPECDAA, "Destroying or damaging property with the intention or recklessness as to endanger life"],
      [OFFTYPECDAA, "Aggravated criminal damage"],
      [OFFTYPECDAA, "Threats to destroy or damage property"],
      [OFFTYPECDAA, "Racially aggravated criminal damage"],
      [OFFTYPECDAA, "Possessing anything with intent to destroy or damage property"],
      [OFFTYPECDAA, "Possessing bladed article / instrument"],
      [OFFTYPECDAA, "Prohibition of the carrying of offensive weapons without lawful authority or reasonable excuse"],
      [OFFTYPECDAA, "Arson"],
      [OFFTYPECDAA, "Aggravated arson"],
      [OFFTYPECDAA, "Racially aggravated arson"],

      # Theft
      [OFFTYPET, "Theft"],
      [OFFTYPET, "Taking conveyance without authority"],
      [OFFTYPET, "Taking or riding a pedal cycle without authority"],
      [OFFTYPET, "Aggravated vehicle taking"],
      [OFFTYPET, "Handling stolen goods"],
      [OFFTYPET, "Receiving property by another's mistake"],
      [OFFTYPET, "Removal of articles from places open to the public"],
      [OFFTYPET, "Abstraction of electricity"],
      [OFFTYPET, "Making off without payment"],
      [OFFTYPET, "Low value shoplifting"],

      # Fraud, Forgery and other Offences of Dishonesty
      [OFFTYPEFFAOOOD, "Fraud (common law)"],
      [OFFTYPEFFAOOOD, "Forgery"],
      [OFFTYPEFFAOOOD, "Copying a false instrument"],
      [OFFTYPEFFAOOOD, "Using a false statement"],
      [OFFTYPEFFAOOOD, "Using a copy of a false instrument"],
      [OFFTYPEFFAOOOD, "Custody or control of false instruments etc."],
      [OFFTYPEFFAOOOD, "Offences relating to money orders, share certificates, passports etc, etc."],
      [OFFTYPEFFAOOOD, "Counterfeiting notes and coins"],
      [OFFTYPEFFAOOOD, "Passing, etc. counterfeiting notes and coins"],
      [OFFTYPEFFAOOOD, "Offences involving the custody/control of counterfeit notes and coins"],
      [OFFTYPEFFAOOOD, "Making, custody or control of counterfeiting materials etc."],
      [OFFTYPEFFAOOOD, "Illegal importation: Counterfeit notes or coins"],
      [OFFTYPEFFAOOOD, "Offences involving the making/custody/control of counterfeiting materials and implements"],
      [OFFTYPEFFAOOOD, "Reproducing British currency"],
      [OFFTYPEFFAOOOD, "Offences in making, etc., imitation of British coins"],
      [OFFTYPEFFAOOOD, "Prohibition of importation of counterfeit note and coins"],
      [OFFTYPEFFAOOOD, "Prohibition of exportation of counterfeit notes and coins"],
      [OFFTYPEFFAOOOD, "Destruction of registers of births etc."],
      [OFFTYPEFFAOOOD, "Making false entries in copies of registers sent to register"],
      [OFFTYPEFFAOOOD, "Fraudulent evasion: counterfeit notes or coins"],
      [OFFTYPEFFAOOOD, "Obtaining services by deception"],
      [OFFTYPEFFAOOOD, "Evasion of liability by deception"],
      [OFFTYPEFFAOOOD, "Obtaining property by deception"],
      [OFFTYPEFFAOOOD, "Obtaining a money transfer by deception"],
      [OFFTYPEFFAOOOD, "Obtaining pecuniary advantage by deception"],
      [OFFTYPEFFAOOOD, "False accounting"],
      [OFFTYPEFFAOOOD, "Liability of company officers for offences of deception committed by the company"],
      [OFFTYPEFFAOOOD, "False statements by company directors"],
      [OFFTYPEFFAOOOD, "Suppression, etc. of documents"],
      [OFFTYPEFFAOOOD, "Procuring execution of a valuable security by deception"],
      [OFFTYPEFFAOOOD, "Advertising rewards for return of goods stolen or lost"],
      [OFFTYPEFFAOOOD, "Dishonestly retaining a wrongful credit"],
      [OFFTYPEFFAOOOD, "Fraudulent use of telecommunication system"],
      [OFFTYPEFFAOOOD, "Possession or supply of anything for fraudulent purpose in connection with use of telecommunication system"],
      [OFFTYPEFFAOOOD, "Offences under the Companies Act 1985"],
      [OFFTYPEFFAOOOD, "Insider dealing"],
      [OFFTYPEFFAOOOD, "False declarations of insolvency in voluntary liquidations"],
      [OFFTYPEFFAOOOD, "Concealment of property and failure to account for losses"],
      [OFFTYPEFFAOOOD, "Concealment or falsification of books and papers"],
      [OFFTYPEFFAOOOD, "False statements"],
      [OFFTYPEFFAOOOD, "Fraudulent disposal of property"],
      [OFFTYPEFFAOOOD, "Absconding with property"],
      [OFFTYPEFFAOOOD, "Fraudulent dealing with property obtained on credit"],
      [OFFTYPEFFAOOOD, "Undischarged bankrupt concerned in a company"],
      [OFFTYPEFFAOOOD, "Failure to keep proper business accounts"],
      [OFFTYPEFFAOOOD, "Misleading statements and practices"],
      [OFFTYPEFFAOOOD, "Fraudulent inducement to make a deposit"],
      [OFFTYPEFFAOOOD, "Counterfeiting customs documents"],
      [OFFTYPEFFAOOOD, "Offences in relation to dies or stamps"],
      [OFFTYPEFFAOOOD, "Counterfeiting of dies or marks"],
      [OFFTYPEFFAOOOD, "Fraudulent application of trademark"],
      [OFFTYPEFFAOOOD, "False application or use of trademarks"],
      [OFFTYPEFFAOOOD, "Forgery of driving documents"],
      [OFFTYPEFFAOOOD, "Forgery and misuse of driving documents"],
      [OFFTYPEFFAOOOD, "Forgery etc. of licenses and other documents"],
      [OFFTYPEFFAOOOD, "Mishandling or falsifying parking documents"],
      [OFFTYPEFFAOOOD, "Forgery, Alteration etc. of documents etc."],
      [OFFTYPEFFAOOOD, "False records or entries relating to driver's hours"],
      [OFFTYPEFFAOOOD, "Forgery, alteration, fraud of licences etc."],
      [OFFTYPEFFAOOOD, "Forgery, alteration etc. of licenses, marks, trade plates etc"],
      [OFFTYPEFFAOOOD, "Forgery of documents etc.: Motor vehicles (EC Type approval)and motor cycles etc. (EC Type approval)"],
      [OFFTYPEFFAOOOD, "Fraudulent evasion of agricultural levy"],
      [OFFTYPEFFAOOOD, "Evasion of duty"],
      [OFFTYPEFFAOOOD, "Trade description offences (9 offences)"],
      [OFFTYPEFFAOOOD, "VAT offences"],

      # Public order offences
      [OFFTYPEPOO, "Breach of any order made by a court"],
      [OFFTYPEPOO, "Causing explosion likely to endanger life or property"],
      [OFFTYPEPOO, "Attempt to cause explosion, making or keeping explosive etc."],
      [OFFTYPEPOO, "Making or possession of explosive under suspicious circumstances"],
      [OFFTYPEPOO, "Bomb Hoaxes"],
      [OFFTYPEPOO, "Contamination of goods with intent"],
      [OFFTYPEPOO, "Placing wood etc. on railway"],
      [OFFTYPEPOO, "Exhibiting false signals etc."],
      [OFFTYPEPOO, "Perjuries (7 offences)"],
      [OFFTYPEPOO, "Offences akin to perjury: False testimony of unsworn child witnesses in criminal proceedings"],
      [OFFTYPEPOO, "Perverting the course of public justice (common law)"],
      [OFFTYPEPOO, "Public nuisance (common law)"],
      [OFFTYPEPOO, "Contempt of court (common law)"],
      [OFFTYPEPOO, "Blackmail"],
      [OFFTYPEPOO, "Corrupt transactions with agents"],
      [OFFTYPEPOO, "Corruption (common law)"],
      [OFFTYPEPOO, "Corruption in public office"],
      [OFFTYPEPOO, "Embracery"],
      [OFFTYPEPOO, "Fabrication of evidence with intent to mislead a tribunal (common law)"],
      [OFFTYPEPOO, "Personation of jurors (common law)"],
      [OFFTYPEPOO, "Concealing an arrestable offence"],
      [OFFTYPEPOO, "Assisting offenders"],
      [OFFTYPEPOO, "False evidence before European Court"],
      [OFFTYPEPOO, "Intimidating a witness, juror etc."],
      [OFFTYPEPOO, "Harming, threatening to harm a witness, juror etc."],
      [OFFTYPEPOO, "Ticket touts"],
      [OFFTYPEPOO, "Prejudicing a drug trafficking investigation"],
      [OFFTYPEPOO, "Giving false statements to procure cremation"],
      [OFFTYPEPOO, "False statement tendered under section 9 of the Criminal Justice Act 1967"],
      [OFFTYPEPOO, "False statement tendered under section 102 of the Magistrates' Courts Act 1980"],
      [OFFTYPEPOO, "Making a false statement to obtain or resist interim possession order"],
      [OFFTYPEPOO, "Making false statement to authorised officer"],
      [OFFTYPEPOO, "Riot"],
      [OFFTYPEPOO, "Violent disorder"],
      [OFFTYPEPOO, "Affray"],
      [OFFTYPEPOO, "Fear or provocation of violence"],
      [OFFTYPEPOO, "Intentional harassment, alarm, or distress"],
      [OFFTYPEPOO, "Harassment, alarm or distress"],
      [OFFTYPEPOO, "Harassment of debtors"],
      [OFFTYPEPOO, "Offence of harassment"],
      [OFFTYPEPOO, "Putting people in fear of violence"],
      [OFFTYPEPOO, "Breach of restraining order/injunction"],
      [OFFTYPEPOO, "Racially aggravated public order offences"],
      [OFFTYPEPOO, "Racially aggravated harassment etc."],
      [OFFTYPEPOO, "Using words or behaviour or displaying written material stirring up racial hatred"],
      [OFFTYPEPOO, "Publishing or distributing written material stirring up racial hatred"],
      [OFFTYPEPOO, "Public performance of play stirring up racial hatred"],
      [OFFTYPEPOO, "Distributing, showing or playing a recording stirring up racial hatred"],
      [OFFTYPEPOO, "Broadcasting programme stirring up racial hatred"],
      [OFFTYPEPOO, "Possession of written material or recording stirring up racial hatred"],
      [OFFTYPEPOO, "Possession of offensive weapon"],
      [OFFTYPEPOO, "Possession of bladed article"],
      [OFFTYPEPOO, "Criminal libel (common law)"],
      [OFFTYPEPOO, "Blasphemy and blasphemous libel (common law)"],
      [OFFTYPEPOO, "Sedition"],
      [OFFTYPEPOO, "Indecent display"],
      [OFFTYPEPOO, "Presentation of obscene performance"],
      [OFFTYPEPOO, "Obstructing railway or carriage on railway"],
      [OFFTYPEPOO, "Obscene articles intended for publication for gain"],
      [OFFTYPEPOO, "Offences of publication of obscene matter"],
      [OFFTYPEPOO, "Agreeing to indemnify sureties"],
      [OFFTYPEPOO, "Absconding by person released on bail"],
      [OFFTYPEPOO, "Personating for purposes of bail etc."],
      [OFFTYPEPOO, "Sending prohibited articles by post"],
      [OFFTYPEPOO, "Impersonating Customs officer"],
      [OFFTYPEPOO, "Obstructing Customs officer"],
      [OFFTYPEPOO, "Penalty on keepers of refreshment houses permitting drunkenness, disorderly conduct, or gaming, etc., therein"],
      [OFFTYPEPOO, "Penalty on persons found drunk"],
      [OFFTYPEPOO, "Drunkenness in a public place"],
      [OFFTYPEPOO, "Drunk in a late night refreshment house"],
      [OFFTYPEPOO, "Drunk while in charge of a child"],
      [OFFTYPEPOO, "Drunk on an aircraft"],
      [OFFTYPEPOO, "Intimidation or annoyance by violence or otherwise"],
      [OFFTYPEPOO, "Offences affecting security"],
      [OFFTYPEPOO, "Offences under the Official Secrets Act 1911, 1920 and 1989"],
      [OFFTYPEPOO, "Unlawful interception of communications by public and private systems"],
      [OFFTYPEPOO, "Disclosure of telecommunication messages"],
      [OFFTYPEPOO, "Incitement to disaffection"],

      # Drug Offences
      [OFFTYPEDO, "Restriction of importation and exportation of controlled drugs"],
      [OFFTYPEDO, "Producing or supplying a Class A, B or C drug"],
      [OFFTYPEDO, "Possession of controlled drugs"],
      [OFFTYPEDO, "Possession of a Class A, B or C drug with intent to supply"],
      [OFFTYPEDO, "Cultivation of cannabis plant"],
      [OFFTYPEDO, "Occupier knowingly permitting drugs offences etc."],
      [OFFTYPEDO, "Activities relating to opium"],
      [OFFTYPEDO, "Prohibition of supply etc., of articles for administering or preparing controlled drugs"],
      [OFFTYPEDO, "Offences relating to the safe custody of controlled drugs"],
      [OFFTYPEDO, "Practitioner contravening drug supply regulations"],
      [OFFTYPEDO, "Incitement"],
      [OFFTYPEDO, "Assisting in or inducing commission outside United Kingdom of offence punishable under a corresponding law"],
      [OFFTYPEDO, "Powers of entry, search and seizure"],
      [OFFTYPEDO, "Illegal importation of Class A, B or C drugs"],
      [OFFTYPEDO, "Fraudulent evasion of controls on Class A, B or C drugs"],
      [OFFTYPEDO, "Failure to disclose knowledge or suspicion of money laundering"],
      [OFFTYPEDO, "Tipping-off in relation to money laundering investigations"],
      [OFFTYPEDO, "Offences in relation to proceeds of drug trafficking"],
      [OFFTYPEDO, "Offences in relation to money laundering investigations"],
      [OFFTYPEDO, "Manufacture and supply of scheduled substances"],
      [OFFTYPEDO, "Drug Trafficking offences at sea"],
      [OFFTYPEDO, "Ships used for illicit traffic"],
      [OFFTYPEDO, "Making and preserving records of production and supply of certain scheduled substances"],
      [OFFTYPEDO, "Supply of intoxicating substance"],

      # Driving and motor vehicle Offences (Other)
      [OFFTYPEDAMVOO, "Dangerous driving"],
      [OFFTYPEDAMVOO, "Careless, and inconsiderate driving"],
      [OFFTYPEDAMVOO, "Driving, or being in charge, when under the influence of drink or drugs"],
      [OFFTYPEDAMVOO, "Driving or being in charge of a motor vehicle with excess alcohol"],
      [OFFTYPEDAMVOO, "Breath tests"],
      [OFFTYPEDAMVOO, "Provision of specimens for analysis"],
      [OFFTYPEDAMVOO, "Motor racing on highways"],
      [OFFTYPEDAMVOO, "Leaving vehicle in dangerous position"],
      [OFFTYPEDAMVOO, "Causing danger to road users"],
      [OFFTYPEDAMVOO, "Restriction of carriage of persons on motor cycles"],
      [OFFTYPEDAMVOO, "Failing to stop at school gate"],
      [OFFTYPEDAMVOO, "Failure to comply with indication given by traffic sign"],
      [OFFTYPEDAMVOO, "Directions to pedestrians"],
      [OFFTYPEDAMVOO, "Using vehicles in dangerous condition"],
      [OFFTYPEDAMVOO, "Contravention of construction and use regulations"],
      [OFFTYPEDAMVOO, "Using etc. motor vehicle without test certificate"],
      [OFFTYPEDAMVOO, "Driving otherwise than in accordance with a licence"],
      [OFFTYPEDAMVOO, "Driving after refusal or revocation of licence"],
      [OFFTYPEDAMVOO, "False declaration as to physical fitness"],
      [OFFTYPEDAMVOO, "Failure to notify disability"],
      [OFFTYPEDAMVOO, "Driving with uncorrected defective eyesight"],
      [OFFTYPEDAMVOO, "Driving while disqualified"],
      [OFFTYPEDAMVOO, "Using etc. motor vehicle without insurance"],
      [OFFTYPEDAMVOO, "Failure to produce driving licence, insurance etc"],
      [OFFTYPEDAMVOO, "Failure to give, or giving false, name and address in case of dangerous or careless or inconsiderate driving or cycling"],
      [OFFTYPEDAMVOO, "Pedestrian contravening constable's direction to stop to give name and address"],
      [OFFTYPEDAMVOO, "Failing to stop and failing to report accident"],
      [OFFTYPEDAMVOO, "Duty of owner of motor vehicle to give information for verifying compliance with requirement of compulsory insurance or security"],
      [OFFTYPEDAMVOO, "Duty to give information as to identity of driver etc., in certain circumstances"],
      [OFFTYPEDAMVOO, "Street playgrounds"],
      [OFFTYPEDAMVOO, "Speeding"],
      [OFFTYPEDAMVOO, "Wanton or furious driving"],
      [OFFTYPEDAMVOO, "Interference with vehicles"],
      [OFFTYPEDAMVOO, "Other road traffic offences (including policing etc.)"],

      # Other
      [OFFTYPEOTHER, "Proceedings for the making of anti-social behaviour orders, sex offender orders etc"],
      [OFFTYPEOTHER, "Failing to keep dogs under proper control resulting in injury and other dog offences"],
      [OFFTYPEOTHER, "Hijacking of aircraft"],
      [OFFTYPEOTHER, "Destroying, damaging or endangering safety of aircraft"],
      [OFFTYPEOTHER, "Other acts endangering or likely to endanger safety of aircraft"],
      [OFFTYPEOTHER, "Offences in relation to certain dangerous articles"],
      [OFFTYPEOTHER, "Endangering safety at aerodromes Hijacking of ships"],
      [OFFTYPEOTHER, "Other offences under the Aviation and Maritime Security Act 1990"],
      [OFFTYPEOTHER, "Piracy"],
      [OFFTYPEOTHER, "Offences under the Football Spectators Act 1989"],
      [OFFTYPEOTHER, "Throwing of missiles"],
      [OFFTYPEOTHER, "Indecent or racialist chanting"],
      [OFFTYPEOTHER, "Going onto the playing area"],
      [OFFTYPEOTHER, "Offences in connection with alcohol on coaches and trains"],
      [OFFTYPEOTHER, "Offences in connection with alcohol, containers etc., at sports grounds"],
      [OFFTYPEOTHER, "Offences of cruelty (Protection of Animals)"],
      [OFFTYPEOTHER, "Penalties for abandonment of animals"],
      [OFFTYPEOTHER, "Offences (Wild Mammals Protection)"],
      [OFFTYPEOTHER, "Raves"],
      [OFFTYPEOTHER, "Offences affecting enjoyment of premises"],
      [OFFTYPEOTHER, "Unlawful eviction and harassment of occupier"],
      [OFFTYPEOTHER, "Use or threat of violence for purpose of securing entry to premises"],
      [OFFTYPEOTHER, "Adverse occupation of residential premises"],
      [OFFTYPEOTHER, "Trespassing during the currency of an interim possession order"],
      [OFFTYPEOTHER, "Interim possession orders: false or misleading statements"],
      [OFFTYPEOTHER, "Aggravated trespass"],
      [OFFTYPEOTHER, "Failure to leave or re-entry to land after police direction to leave"],
      [OFFTYPEOTHER, "Unauthorised campers"],
    ].freeze

    def initialize(type, description)
      @type = type
      @description = description
    end

    def self.all
      @all ||= OFFENCES.map { |type, desc| new(type, desc) }
    end

    def name
      description
    end

    def as_json(*)
      {
        type: type,
        name: description,
        search_value: "#{type} #{description}".downcase,
      }
    end
  end
end
