name: Test, Build, Scan & Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64
        with:
          bundler-cache: true
      
      - name: Run Rubocop linter
        run: bundle exec rubocop --format github --format progress

  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code 
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64
        with:
          bundler-cache: true
      
      - name: Run RSpec tests
        run: |
          RUBYOPT=-W:no-deprecated \
          bundle exec rspec --format progress

      - name: Upload code coverage results
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: coverage-results
          path: coverage
          include-hidden-files: true